# Generated by Django 4.2.11 on 2026-06-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog", "博客文章"),
                            ("video", "视频内容"),
                            ("code", "代码片段"),
                        ],
                        default="blog",
                        max_length=10,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="内容简介"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="封面图",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", verbose_name="正文内容（博客文章）"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/",
                        verbose_name="视频文件（mp4）",
                    ),
                ),
                (
                    "video_desc",
                    models.TextField(blank=True, default="", verbose_name="视频简介"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="python",
                        max_length=50,
                        verbose_name="编程语言",
                    ),
                ),
                (
                    "code_content",
                    models.TextField(blank=True, default="", verbose_name="代码内容"),
                ),
                (
                    "code_desc",
                    models.TextField(blank=True, default="", verbose_name="代码说明"),
                ),
            ],
            options={
                "verbose_name": "内容",
                "verbose_name_plural": "内容",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Honor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="奖项名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="奖项描述"),
                ),
                (
                    "award_date",
                    models.DateField(blank=True, null=True, verbose_name="获奖日期"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="排序（数字越小越靠前）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "荣誉奖项",
                "verbose_name_plural": "荣誉奖项",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="陆焱烨", max_length=50, verbose_name="姓名"
                    ),
                ),
                (
                    "grade_major",
                    models.CharField(
                        default="计算机242班 大二在读",
                        max_length=100,
                        verbose_name="年级专业",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "intro",
                    models.TextField(blank=True, default="", verbose_name="个人简介"),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        default="Python,Java,C++,HTML/CSS,JavaScript",
                        max_length=255,
                        verbose_name="技术栈标签（逗号分隔）",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人信息",
                "verbose_name_plural": "个人信息",
            },
        ),
    ]
