# Generated by Django 4.2.11 on 2026-06-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACMTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目标题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("01背包", "01背包DP"),
                            ("区间DP", "区间DP"),
                            ("基础DP", "基础DP"),
                            ("完全背包", "完全背包"),
                            ("数位DP", "数位DP"),
                            ("其他", "其他"),
                        ],
                        default="其他",
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "problem_id",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="题目编号"
                    ),
                ),
                ("code", models.TextField(verbose_name="代码内容")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="题目说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
            ],
            options={
                "verbose_name": "算法板子",
                "verbose_name_plural": "算法板子",
                "ordering": ["category", "-created_at"],
            },
        ),
    ]
